# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b140054ba924cd4eb34e4824c3d74bc9c318a57f6c0c7f201dce15b52b83d73329c31c77d0250233646fb36fe099ddc8b663bbd6959e48d11cebec85dfae75f

test:
  secret_key_base: ebd5cd0855545347b3f600bdcfe3ea8b07a45c1745ab77b5203378bee1fe4abe312e185c7e170192c2636c3039f1c80cf98c7b97a656b7e4182543a3faa03599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
